spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: Tameem
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Hello Ayisha
server:
  port: '8082'
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
